### ISSUE TITLE
More efficient way of updating the placeholders

### ISSUE THREAD

**Issue by MrIvanPlays** [ArcanePlugins/PAPISigns#3]
Currently, the plugin updates it's placeholders on PlayerMoveEvent. It works fine, but given that PlayerMoveEvent is called _literally_ every tick, this is not a great way of doing things.

**Comment by lokka30** [comment]
Events to consider:
- PlayerTeleportEvent (when a player teleports, load all the signs in)
- PlayerChangedWorldEvent (when a player changes world, load all the signs in)
- PlayerJoinEvent (when a player joins, load all the signs in)
- BlockPlaceEvent (when signs are placed, do an update for that specific sign)
- and lastly, a repeating task of 7 seconds interval. If the player hasn't moved since the last check, don't do an update.

**Comment by MrIvanPlays** [comment]
There isn't any suitable way of doing this afaik, and I need a 1.20 compatible release, so _for now_ atleast I'm gonna close this as resolved.
